EXERCISE_CATALOG = [
    {"name": "Bench Press", "category": "Chest", "type": "strength"},
    {"name": "Incline Dumbbell Press", "category": "Chest", "type": "strength"},
    {"name": "Push-ups", "category": "Chest", "type": "strength"},
    {"name": "Cable Flyes", "category": "Chest", "type": "strength"},
    {"name": "Deadlift", "category": "Back", "type": "strength"},
    {"name": "Pull-ups", "category": "Back", "type": "strength"},
    {"name": "Lat Pulldown", "category": "Back", "type": "strength"},
    {"name": "Bent-over Row", "category": "Back", "type": "strength"},
    {"name": "Squats", "category": "Legs", "type": "strength"},
    {"name": "Leg Press", "category": "Legs", "type": "strength"},
    {"name": "Lunges", "category": "Legs", "type": "strength"},
    {"name": "Hamstring Curl", "category": "Legs", "type": "strength"},
    {"name": "Shoulder Press", "category": "Shoulders", "type": "strength"},
    {"name": "Lateral Raise", "category": "Shoulders", "type": "strength"},
    {"name": "Front Raise", "category": "Shoulders", "type": "strength"},
    {"name": "Bicep Curls", "category": "Arms", "type": "strength"},
    {"name": "Hammer Curls", "category": "Arms", "type": "strength"},
    {"name": "Tricep Dips", "category": "Arms", "type": "strength"},
    {"name": "Tricep Pushdown", "category": "Arms", "type": "strength"},
    {"name": "Plank", "category": "Core", "type": "timer"},
    {"name": "Sit-ups", "category": "Core", "type": "strength"},
    {"name": "Russian Twist", "category": "Core", "type": "timer"},
    {"name": "Mountain Climbers", "category": "Core", "type": "timer"},
    {"name": "Burpees", "category": "Full Body", "type": "strength"},
    {"name": "Kettlebell Swing", "category": "Full Body", "type": "strength"},
    {"name": "Jumping Jacks", "category": "Full Body", "type": "timer"},
]